### **Partial Pivoting in Gaussian Elimination**

### **1. Swapping Rows in Python**
Define the matrix:

$ A = \begin{bmatrix}2 & 1 & 2 \\ 3 & 5 & 2 \\ 7 & 4 & 4 \end{bmatrix} $  

We want to swap the first and third row. We can do this by defining a new variable that holds the first row. We can then assign the other row to row 0, and use our hold row variable to assign row zero to row 2.

Print A to make sure that you have done it correctly.  


In [ ]:
import numpy as np

A = np.array([[2,1,2],[3,5,2],[7,4,4]])

holdRow = A[0,:]

A[0,:] = A[2,:]
A[2,:] = holdRow

print('New A:\n',A)

New A:
 [[7 4 4]
 [3 5 2]
 [7 4 4]]


**You may have noticed that it didn't do what we expected it to.** 


#### **2. Debugging the Faulty Swap**

You shlould see that two of the rows are the same!. 

This is due to one of the ways that python stores variables. When you assign a variable to be a collection of elements in an array, python stores an ailias of those arrays. This means that changes to our variable, or changes to the array with change the counterpart as well. 

In this case when we change the first row to be [7,4,4], we also change holdRow to be [7,4,4] because holdRow is always equal to the first row of A, even if that value has changed. 

To see this in action, paste the code from the previous section below and print out the holdRow variables right after they are assigned and right after the swap is perfomed. 

In [ ]:
A = np.array([[2,1,2],[3,5,2],[7,4,4]])

holdRow = A[0,:]

print('holdRow before the swap=', holdRow,'\n')

A[0,:] = A[2,:]
A[2,:] = holdRow

print('holdRow after the swap=', holdRow,'\n')

print('New A:\n',A)

holdRow before the swap= [2 1 2] 

holdRow after the swap= [7 4 4] 

New A:
 [[7 4 4]
 [3 5 2]
 [7 4 4]]


#### **3. Using .copy()**

The solution to this problem is quite simple. Create a copy of row 0 by adding .copy() on to the end of the creation of holdRow. This assigns the holdRow variable as an independant COPY of the respective row of A and therfore will not change when we rewrite the rows of A.

Try the swap again but use .copy()

In [ ]:
A = np.array([[2,1,2],[3,5,2],[7,4,4]])

holdRow = A[0,:].copy()

print('holdRow before the swap=', holdRow,'\n')

A[0,:] = A[2,:]
A[2,:] = holdRow

print('holdRow after the swap=', holdRow,'\n')

print('New A:\n',A)

holdRow before the swap= [2 1 2] 

holdRow after the swap= [2 1 2] 

New A:
 [[7 4 4]
 [3 5 2]
 [2 1 2]]


#### **4. Finding the Maximum Value in a Column**

Now that we know how to swap rows, let's put this to good use.

When performing gaussian elimination, dividing by the largest possible number can reduce roundoff error. Therefore we want to move the row containing the largest element in each column to the diagonal by swappping the equation with the one that currently sits at the pivot. Remember that negaitve values are valid too, so use the absolute value of the elements in the column to find the max.

Given the matrix C below:

$ C = \begin{bmatrix}2 & 1 & 0 & 3 \\ 6 & 4 & 7 & 3 \\ 4 & 8 & 12 & 5 \\ 9 & 10 & 2 & 5\end{bmatrix} $

Use the numpy function argmax() to find the location of the largest element in the first column, print the number of the row and the value of that element.  Swap that row with the first row and print the new C.

In [ ]:
C = np.array([[2,1,0,3],[6,4,7,3],[4,8,12,5],[9,10,2,5]])

maxLoc = np.argmax(abs(C[:,0]))
print('location of max in column 0 is :',maxLoc)
print('The max in column 0 is:',max(C[:,0]))

holdRow = C[0,:].copy()
C[0,:] = C[maxLoc,:]
C[maxLoc,:] = holdRow

print('\n the new C:\n', C)


location of max in column 0 is : 3
The max in column 0 is: 9

 the new C:
 [[ 9 10  2  5]
 [ 6  4  7  3]
 [ 4  8 12  5]
 [ 2  1  0  3]]


#### **5. Adding Pivoting to Gaussian Elimination**

We want to apply pivoting to Gaussian Elimination. To speed the process, the basic gaussian elimination code from pg. 41 of the textbook is provided below.

In the second code block, modify the function to pivot before the elimination of each column. You may copy/paste the code from the textbook or use your own Gaussian elimination code if you choose, but leave the original textbook function to be used for comparison. 

When Looking at the textbook code, answer these questions to get started with the modifications.



1.   What does the variable k represent?
2.   What does the variable i represent?
3.   When do we want to swap rows?
4.   Where in the code does the row swapping go?
5.   Which rows should we look for he max value in at each step?



Test your code against the textbook code using the matrix C and the vector B given below:

$ C = \begin{bmatrix}2 & 1 & 0 & 3 \\ 6 & 4 & 7 & 3 \\ 4 & 8 & 12 & 5 \\ 9 & 10 & 2 & 5\end{bmatrix} B = \begin{bmatrix} 9 \\ 5 \\ 4\\ 1\end{bmatrix}$ 

Compute your residual by computing $|Cx-B|$ and compare your the result to the residual you get from the non-pivoted example.

In [ ]:
from numpy.core.memmap import dtype
# TEXTBOOK CODE - DO NOT ALTER

C = np.array([[2,1,0,3],[6,4,7,3],[4,8,12,5],[9,10,2,5]],dtype = float)
B = np.array([[9],[5],[4],[1]],dtype = float)

def gaussElimin(a,b):
  n = len(b)
  #Elimination Phase
  for k in range(0,n-1):
    for i in range(k+1,n):
      if a[i,k] != 0.0:
        lam = a[i,k]/a[k,k]
        a[i,k:n] = a[i,k:n] - lam*a[k,k:n]
        b[i] = b[i] - lam*b[k]
  #Back Substitution
  for k in range(n-1,-1,-1):
    b[k] = (b[k] - np.dot(a[k,k+1:n],b[k+1:n]))/a[k,k]
  return b

gauss = gaussElimin(C,B)
print('Final Solution = \n',gauss)

Final Solution = 
 [[ 0.30322581]
 [-1.90322581]
 [ 0.07096774]
 [ 3.43225806]]


In [ ]:
# ADD PARTIAL PIVOTING HERE

C = np.array([[2,1,0,3],[6,4,7,3],[4,8,12,5],[9,10,2,5]],dtype = float)
B = np.array([[9],[5],[4],[1]],dtype = float)


def gaussEliminPartPivot(a,b):
  n = len(b)
  #Elimination Phase
  for pivot in range(0,n-1):

    #find the max 
    maxLoc = np.argmax(abs(a[pivot:,pivot]))+pivot
    print('location of max in column', pivot, ' is :',maxLoc)
    print('The max in column', pivot, ' is:',max(abs(a[:,pivot])),'\n')

    #Store row
    holdRow = a[pivot,:].copy()
    holdb = b[pivot]*1

    #Swap Rows
    a[pivot,:] = a[maxLoc,:] 
    a[maxLoc,:] = holdRow
    b[pivot] = b[maxLoc]
    b[maxLoc] = holdb
    

    print('A and B after pivoting for pivot = ', pivot, '\n')
    print(a,'\n\n',b,'\n')

    for row in range(pivot+1,n):
      if a[row,pivot] != 0.0:
        lam = a[row,pivot]/a[pivot,pivot]
        a[row,pivot:n] = a[row,pivot:n] - lam*a[pivot,pivot:n]
        b[row] = b[row] - lam*b[pivot]
    print('A and B after the elimination of column', pivot, '\n')
    print(a,'\n\n',b,'\n')
  #Back Substitution
  for k in range(n-1,-1,-1):
    b[k] = (b[k] - np.dot(a[k,k+1:n],b[k+1:n]))/a[k,k]
  return b
gaussPiv = gaussEliminPartPivot(C,B)
print('Final Solution  = \n',gaussPiv)

print('\nlets make sure we get the same thing as before\n')



C = np.array([[2,1,0,3],[6,4,7,3],[4,8,12,5],[9,10,2,5]],dtype = float)
B = np.array([[9],[5],[4],[1]],dtype = float)

residual = abs(C@gaussPiv - B)
print('Residual for Pivoted\n')
print(residual)


residual = abs(C@gauss - B)
print('\nResidual for non-Pivoted\n')
print(residual)

location of max in column 0  is : 3
The max in column 0  is: 9.0 

A and B after pivoting for pivot =  0 

[[ 9. 10.  2.  5.]
 [ 6.  4.  7.  3.]
 [ 4.  8. 12.  5.]
 [ 2.  1.  0.  3.]] 

 [[1.]
 [5.]
 [4.]
 [9.]] 

A and B after the elimination of column 0 

[[ 9.         10.          2.          5.        ]
 [ 0.         -2.66666667  5.66666667 -0.33333333]
 [ 0.          3.55555556 11.11111111  2.77777778]
 [ 0.         -1.22222222 -0.44444444  1.88888889]] 

 [[1.        ]
 [4.33333333]
 [3.55555556]
 [8.77777778]] 

location of max in column 1  is : 2
The max in column 1  is: 10.0 

A and B after pivoting for pivot =  1 

[[ 9.         10.          2.          5.        ]
 [ 0.          3.55555556 11.11111111  2.77777778]
 [ 0.         -2.66666667  5.66666667 -0.33333333]
 [ 0.         -1.22222222 -0.44444444  1.88888889]] 

 [[1.        ]
 [3.55555556]
 [4.33333333]
 [8.77777778]] 

A and B after the elimination of column 1 

[[ 9.         10.          2.          5.        ]
 [ 0.

#### **6. Scaled Partial Pivoting**

Roundoff error can be reduced even further if, when matrix is pivoted, and the pivot row is scaled so that the largest element in the equation is set to 1.

Modify the code above to divide each pivot row by its largest element.

Compare the result to the values you get from the non-pivoted example and the regular partially pivoted solution.




In [ ]:
C = np.array([[2,1,0,3],[6,4,7,3],[4,8,12,5],[9,10,2,5]],dtype = float)
B = np.array([[9],[5],[4],[1]],dtype = float)

def gaussEliminScalePivot(a,b):
  n = len(b)
  #Elimination Phase
  for pivot in range(0,n-1):

    #find the max 
    maxLoc = np.argmax(abs(a[pivot:,pivot]))+pivot
    print('location of max in column', pivot, ' is :',maxLoc)
    print('The max in column', pivot, ' is:',max(abs(a[:,pivot])),'\n')

    #Store row
    holdRow = a[pivot,:].copy()
    holdb = b[pivot]*1

    #Swap Rows
    a[pivot,:] = a[maxLoc,:] 
    a[maxLoc,:] = holdRow
    b[pivot] = b[maxLoc]
    b[maxLoc] = holdb
    

    #Scale Rows
    scaleFactor = max(abs(a[pivot,:]))
    b[pivot] = b[pivot]/scaleFactor
    a[pivot,:] = a[pivot,:]/scaleFactor

    print('A and B after pivoting for pivot = ', pivot, '\n')
    print(a,'\n\n',b,'\n')

    for row in range(pivot+1,n):
      if a[row,pivot] != 0.0:
        lam = a[row,pivot]/a[pivot,pivot]
        a[row,pivot:n] = a[row,pivot:n] - lam*a[pivot,pivot:n]
        b[row] = b[row] - lam*b[pivot]
    print('A and B after the elimination of column', pivot, '\n')
    print(a,'\n\n',b,'\n')
  #Back Substitution
  for k in range(n-1,-1,-1):
    b[k] = (b[k] - np.dot(a[k,k+1:n],b[k+1:n]))/a[k,k]
  return b
gaussScalePiv = gaussEliminScalePivot(C,B)
print('Final Solution  = \n',gaussPiv)

print('\nlets make sure we get the same thing as before\n')



C = np.array([[2,1,0,3],[6,4,7,3],[4,8,12,5],[9,10,2,5]],dtype = float)
B = np.array([[9],[5],[4],[1]],dtype = float)

residual = abs(C@gaussScalePiv - B)
print('Residual for Scaled Pivoted\n')
print(residual)

residual = abs(C@gaussPiv - B)
print('\nResidual for Pivoted\n')
print(residual)


residual = abs(C@gauss - B)
print('\nResidual for non-Pivoted\n')
print(residual)

location of max in column 0  is : 3
The max in column 0  is: 9.0 

A and B after pivoting for pivot =  0 

[[ 0.9  1.   0.2  0.5]
 [ 6.   4.   7.   3. ]
 [ 4.   8.  12.   5. ]
 [ 2.   1.   0.   3. ]] 

 [[0.1]
 [5. ]
 [4. ]
 [9. ]] 

A and B after the elimination of column 0 

[[ 0.9         1.          0.2         0.5       ]
 [ 0.         -2.66666667  5.66666667 -0.33333333]
 [ 0.          3.55555556 11.11111111  2.77777778]
 [ 0.         -1.22222222 -0.44444444  1.88888889]] 

 [[0.1       ]
 [4.33333333]
 [3.55555556]
 [8.77777778]] 

location of max in column 1  is : 2
The max in column 1  is: 3.5555555555555554 

A and B after pivoting for pivot =  1 

[[ 0.9         1.          0.2         0.5       ]
 [ 0.          0.32        1.          0.25      ]
 [ 0.         -2.66666667  5.66666667 -0.33333333]
 [ 0.         -1.22222222 -0.44444444  1.88888889]] 

 [[0.1       ]
 [0.32      ]
 [4.33333333]
 [8.77777778]] 

A and B after the elimination of column 1 

[[9.0000000e-01 1.0000

#### **7. Why Scale or Pivot?**

For the previous problems we can see that there is very little difference between the different methods. Let's look at some cases where that is not the case. Use the matrix:

$A = \begin{bmatrix}600 & 0 & 1\times10^{15} & 13 \\ 1\times10^{13} & 5 & 0 & 7 \\ 1 & 3 & 5 & 17 \\ 1 & 1\times10^{-6} & 2 & 5\end{bmatrix} $

and the same B vector and compare the residuals between scaled and partial and scaled and regular.

In [ ]:
A = np.array([[600,0,1e15,13],[1e13,5,0,7],[1,3,5,17],[1,1e-6,2,5]],dtype = float)
B = np.array([[9],[5],[4],[1]],dtype = float)

scaled = gaussEliminScalePivot(A.copy(),B.copy())


regular = gaussElimin(A.copy(),B.copy())


pivoted = gaussEliminPartPivot(A.copy(),B.copy())

residual = abs(A@scaled - B)
print('Residual for Scaled Pivoted\n')
print(residual)

residual = abs(A@pivoted - B)
print('\nResidual for Pivoted\n')
print(residual)


residual = abs(A@regular - B)
print('\nResidual for non-Pivoted\n')
print(residual)


location of max in column 0  is : 1
The max in column 0  is: 10000000000000.0 

A and B after pivoting for pivot =  0 

[[1.0e+00 5.0e-13 0.0e+00 7.0e-13]
 [6.0e+02 0.0e+00 1.0e+15 1.3e+01]
 [1.0e+00 3.0e+00 5.0e+00 1.7e+01]
 [1.0e+00 1.0e-06 2.0e+00 5.0e+00]] 

 [[5.e-13]
 [9.e+00]
 [4.e+00]
 [1.e+00]] 

A and B after the elimination of column 0 

[[ 1.000000e+00  5.000000e-13  0.000000e+00  7.000000e-13]
 [ 0.000000e+00 -3.000000e-10  1.000000e+15  1.300000e+01]
 [ 0.000000e+00  3.000000e+00  5.000000e+00  1.700000e+01]
 [ 0.000000e+00  9.999995e-07  2.000000e+00  5.000000e+00]] 

 [[5.e-13]
 [9.e+00]
 [4.e+00]
 [1.e+00]] 

location of max in column 1  is : 2
The max in column 1  is: 2.9999999999995 

A and B after pivoting for pivot =  1 

[[ 1.00000000e+00  5.00000000e-13  0.00000000e+00  7.00000000e-13]
 [ 0.00000000e+00  1.76470588e-01  2.94117647e-01  1.00000000e+00]
 [ 0.00000000e+00 -3.00000000e-10  1.00000000e+15  1.30000000e+01]
 [ 0.00000000e+00  9.99999500e-07  2.00000000e