### **Partial Pivoting in Gaussian Elimination**

### **1. Swapping Rows in Python**
Define the matrix:

$ A = \begin{bmatrix}2 & 1 & 2 \\ 3 & 5 & 2 \\ 7 & 4 & 4 \end{bmatrix} $  

We want to swap the first and third row. We can do this by defining a new variable that holds the first row. We can then assign the other row to row 0, and use our hold row variable to assign row zero to row 2.

Print A to make sure that you have done it correctly.  


In [10]:
import numpy as np

A = np.array([[2,1,2],[3,5,2],[7,4,4]])

holdRow = A[0,:]

A[0,:] = A[2,:]

A[2,:] = holdRow

print(A)

[[7 4 4]
 [3 5 2]
 [7 4 4]]


**You may have noticed that it didn't do what we expected it to.** 


#### **2. Debugging the Faulty Swap**

You shlould see that two of the rows are the same!. 

This is due to one of the ways that python stores variables. When you assign a variable to be a collection of elements in an array, python stores an ailias of those arrays. This means that changes to our variable, or changes to the array with change the counterpart as well. 

In this case when we change the first row to be [7,4,4], we also change holdRow to be [7,4,4] because holdRow is always equal to the first row of A, even if that value has changed. 

To see this in action, paste the code from the previous section below and print out the holdRow variables right after they are assigned and right after the swap is perfomed. 

In [13]:
A = np.array([[2,1,2],[3,5,2],[7,4,4]])


holdRow = A[0,:]

print(holdRow)

A[0,:] = A[2,:]

print(holdRow)

A[2,:] = holdRow

#print(A)


[2 1 2]
[7 4 4]


#### **3. Using .copy()**

The solution to this problem is quite simple. Create a copy of row 0 by adding .copy() on to the end of the creation of holdRow. This assigns the holdRow variable as an independant COPY of the respective row of A and therfore will not change when we rewrite the rows of A.

Try the swap again but use .copy()

In [15]:
A = np.array([[2,1,2],[3,5,2],[7,4,4]])

holdRow = A[0,:].copy()

A[0,:] = A[2,:]

A[2,:] = holdRow

print(A)

[[7 4 4]
 [3 5 2]
 [2 1 2]]


#### **4. Finding the Maximum Value in a Column**

Now that we know how to swap rows, let's put this to good use.

When performing gaussian elimination, dividing by the largest possible number can reduce roundoff error. Therefore we want to move the row containing the largest element in each column to the diagonal by swappping the equation with the one that currently sits at the pivot. Remember that negaitve values are valid too, so use the absolute value of the elements in the column to find the max.

Given the matrix C below:

$ C = \begin{bmatrix}2 & 1 & 0 & 3 \\ 6 & 4 & 7 & 3 \\ 4 & 8 & 12 & 5 \\ 9 & 10 & 2 & 5\end{bmatrix} $

Use the numpy function argmax() to find the location of the largest element in the first column, print the number of the row and the value of that element.  Swap that row with the first row and print the new C.

In [20]:
C = np.array([[2,1,0,3],[6,4,7,3],[4,8,12,5],[9,10,2,5]],dtype = float)

maxx = np.argmax(C[:,0])

holdRow = C[0,:].copy()
C[0,:] = C[maxx,:]
C[maxx,:] = holdRow

print(C)

[[ 9. 10.  2.  5.]
 [ 6.  4.  7.  3.]
 [ 4.  8. 12.  5.]
 [ 2.  1.  0.  3.]]


#### **5. Adding Pivoting to Gaussian Elimination**

We want to apply pivoting to Gaussian Elimination. To speed the process, the basic gaussian elimination code from pg. 41 of the textbook is provided below.

In the second code block, modify the function to pivot before the elimination of each column. You may copy/paste the code from the textbook or use your own Gaussian elimination code if you choose, but leave the original textbook function to be used for comparison. 

When Looking at the textbook code, answer these questions to get started with the modifications.



1.   What does the variable k represent?
2.   What does the variable i represent?
3.   When do we want to swap rows?
4.   Where in the code does the row swapping go?
5.   Which rows should we look for he max value in at each step?



Test your code against the textbook code using the matrix C and the vector B given below:

$ C = \begin{bmatrix}2 & 1 & 0 & 3 \\ 6 & 4 & 7 & 3 \\ 4 & 8 & 12 & 5 \\ 9 & 10 & 2 & 5\end{bmatrix} B = \begin{bmatrix} 9 \\ 5 \\ 4\\ 1\end{bmatrix}$ 

Compute your residual by computing $|Cx-B|$ and compare your the result to the residual you get from the non-pivoted example.

In [21]:
from numpy.core.memmap import dtype
# TEXTBOOK CODE - DO NOT ALTER

C = np.array([[2,1,0,3],[6,4,7,3],[4,8,12,5],[9,10,2,5]],dtype = float)
B = np.array([[9],[5],[4],[1]],dtype = float)

# Cx = b

def gaussElimin(a,b):
  n = len(b)
  #Elimination Phase
  for k in range(0,n-1):
    for i in range(k+1,n):
      if a[i,k] != 0.0:
        lam = a[i,k]/a[k,k]
        a[i,k:n] = a[i,k:n] - lam*a[k,k:n]
        b[i] = b[i] - lam*b[k]
  #Back Substitution
  for k in range(n-1,-1,-1):
    b[k] = (b[k] - np.dot(a[k,k+1:n],b[k+1:n]))/a[k,k]
  return b

gauss = gaussElimin(C,B)
print('Final Solution = \n',gauss)

Final Solution = 
 [[ 0.30322581]
 [-1.90322581]
 [ 0.07096774]
 [ 3.43225806]]


In [22]:
C = np.array([[2,1,0,3],[6,4,7,3],[4,8,12,5],[9,10,2,5]],dtype = float)
B = np.array([[9],[5],[4],[1]],dtype = float)

def gaussEliminPP(a,b):
  n = len(b)
  #Elimination Phase
  for k in range(0,n-1):

    maxLoc = np.argmax(a[k:,k])+k

    holdRow = a[k,:].copy()
    a[k,:] = a[maxLoc,:]
    a[maxLoc,:] = holdRow

    holdb = b[k].copy()
    b[k] = b[maxLoc]
    b[maxLoc] = holdb

    for i in range(k+1,n):
      if a[i,k] != 0.0:
        lam = a[i,k]/a[k,k]
        a[i,k:n] = a[i,k:n] - lam*a[k,k:n]
        b[i] = b[i] - lam*b[k]
  #Back Substitution
  for k in range(n-1,-1,-1):
    b[k] = (b[k] - np.dot(a[k,k+1:n],b[k+1:n]))/a[k,k]
  return b

gaussPP = gaussEliminPP(C,B)
print('Final Solution = \n',gaussPP)

Final Solution = 
 [[ 0.30322581]
 [-1.90322581]
 [ 0.07096774]
 [ 3.43225806]]


#### **6. Scaled Partial Pivoting**

Roundoff error can be reduced even further if, when matrix is pivoted, and the pivot row is scaled so that the largest element in the equation is set to 1.

Modify the code above to divide each pivot row by its largest element.

Compare the result to the values you get from the non-pivoted example and the regular partially pivoted solution.




In [23]:
C = np.array([[2,1,0,3],[6,4,7,3],[4,8,12,5],[9,10,2,5]],dtype = float)
B = np.array([[9],[5],[4],[1]],dtype = float)

def gaussEliminSPP(a,b):
  n = len(b)
  #Elimination Phase
  for k in range(0,n-1):

    maxLoc = np.argmax(a[k:,k])+k

    holdRow = a[k,:].copy()
    a[k,:] = a[maxLoc,:]
    a[maxLoc,:] = holdRow

    holdb = b[k].copy()
    b[k] = b[maxLoc]
    b[maxLoc] = holdb

    aMax = max(abs(a[k,:]))

    a[k,:] = a[k,:]/aMax
    b[k] = b[k]/aMax

    for i in range(k+1,n):
      if a[i,k] != 0.0:
        lam = a[i,k]/a[k,k]
        a[i,k:n] = a[i,k:n] - lam*a[k,k:n]
        b[i] = b[i] - lam*b[k]
  #Back Substitution
  for k in range(n-1,-1,-1):
    b[k] = (b[k] - np.dot(a[k,k+1:n],b[k+1:n]))/a[k,k]
  return b

gaussSPP = gaussEliminSPP(C,B)
print('Final Solution = \n',gaussSPP)

Final Solution = 
 [[ 0.30322581]
 [-1.90322581]
 [ 0.07096774]
 [ 3.43225806]]


#### **7. Why Scale or Pivot?**

For the previous problems we can see that there is very little difference between the different methods. Let's look at some cases where that is not the case. Use the matrix:

$A = \begin{bmatrix}600 & 0 & 1\times10^{15} & 13 \\ 1\times10^{13} & 5 & 0 & 7 \\ 1 & 3 & 5 & 17 \\ 1 & 1\times10^{-6} & 2 & 5\end{bmatrix} $

and the same B vector and compare the residuals between scaled and partial and scaled and regular.

In [27]:
A = np.array([[600,0,1e15,13],[1e13,5,0,7],[1,3,5,17],[1,1e-6,2,5]],dtype = float)
B = np.array([[9],[5],[4],[1]],dtype = float)

gauss = gaussElimin(A.copy(),B.copy())
gaussPP = gaussEliminPP(A.copy(),B.copy())
gaussSPP = gaussEliminSPP(A.copy(),B.copy())

print('normal gauss residual: \n', abs(A @ gauss - B))
print()
print('pp gauss residual: \n', abs(A @ gaussPP - B))
print()
print('spp gauss residual: \n', abs(A @ gaussSPP - B))

normal gauss residual: 
 [[0.00000000e+00]
 [5.98606695e-06]
 [6.80005656e-07]
 [1.47681867e-12]]

pp gauss residual: 
 [[0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.11022302e-16]]

spp gauss residual: 
 [[0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.11022302e-16]]
